apiVersion: v1
kind: Service
metadata:
  labels:
    app: reporting-service
  name: reporting-service
  namespace: production
spec:
  clusterIP: 10.1.85.225
  clusterIPs:
  - 10.1.85.225
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8006
    protocol: TCP
    targetPort: 8006
  selector:
    app: reporting-service
  sessionAffinity: None
  type: ClusterIP
