apiVersion: v1
kind: Service
metadata:
  labels:
    app: rules-service
  name: rules-service
  namespace: production
spec:
  clusterIP: 10.1.148.56
  clusterIPs:
  - 10.1.148.56
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: rules-service
  sessionAffinity: None
  type: ClusterIP
