apiVersion: v1
kind: Service
metadata:
  name: rules-service
  namespace: production
  labels: { app: rules-service }
spec:
  type: ClusterIP
  selector: { app: rules-service }
  ports:
    - { name: http, port: 8003, targetPort: 8003 }
