sonar.organization=ashutosh9199
sonar.projectKey=ashutosh9199_terraform-review-assistant-microservices
sonar.sources=apps
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/__pycache__/**,**/*.test.tsx,**/*.test.ts
sonar.tests=apps/api-gateway/tests
sonar.python.version=3.11
