import { Science as TestIcon } from '@mui/icons-material';
import {
  Alert,
  Autocomplete,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  Stack,
  TextField,
  Typography
} from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';
import { useState } from 'react';
import { getLlmSettings, saveLlmSettings, testLlmSettings } from '../api/queries';
import { detectProvider, findProvider, PROVIDERS, ProviderId } from '../llmProviders';

function errorDetail(error: unknown): string {
  const detail = (error as AxiosError<{ detail?: string }>)?.response?.data?.detail;
  return detail ?? 'Request failed.';
}

/**
 * Blocks the entire app until a working LLM connection is configured. This app's
 * review quality depends on the AI agents, so an unconfigured or broken key must
 * not be silently bypassed (which is exactly the issue this fixes: a stored key
 * that quietly fell back to an offline heuristic with no signal to the user).
 * The "Save & Continue" button only enables after a real, successful test call.
 */
export function LlmOnboardingModal() {
  const queryClient = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ['llm-settings'], queryFn: getLlmSettings });

  const [provider, setProvider] = useState<ProviderId>('auto');
  const [endpoint, setEndpoint] = useState('');
  const [model, setModel] = useState('');
  const [apiKey, setApiKey] = useState('');
  const [tested, setTested] = useState(false);

  const providerOption = findProvider(provider);

  function onApiKeyChange(value: string) {
    setApiKey(value);
    setTested(false);
    if (provider === 'auto' && value.length >= 8) {
      const detected = detectProvider(value, endpoint, model);
      if (detected !== 'auto') setProvider(detected);
    }
  }

  const testMutation = useMutation({
    mutationFn: () =>
      testLlmSettings({
        api_key: apiKey,
        endpoint: endpoint || undefined,
        model: model || undefined,
        provider: provider === 'auto' ? undefined : provider
      }),
    onSuccess: () => setTested(true)
  });

  const saveMutation = useMutation({
    mutationFn: () =>
      saveLlmSettings({
        api_key: apiKey,
        endpoint: endpoint || undefined,
        model: model || undefined,
        provider: provider === 'auto' ? undefined : provider
      }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['llm-settings'] })
  });

  if (isLoading || data?.has_api_key) {
    return null;
  }

  return (
    <Dialog
      open
      disableEscapeKeyDown
      onClose={() => {
        /* intentionally not closable except via the gated Save & Continue action below */
      }}
      maxWidth="sm"
      fullWidth
    >
      <DialogTitle>Connect an LLM provider to continue</DialogTitle>
      <DialogContent>
        <Stack spacing={2.5} sx={{ mt: 1 }}>
          <Typography color="text.secondary">
            This application's reviews are generated by AI agents. Add and verify a working LLM
            connection before continuing &mdash; this step can't be skipped.
          </Typography>

          <FormControl fullWidth>
            <InputLabel>Provider</InputLabel>
            <Select
              label="Provider"
              value={provider}
              onChange={(event) => {
                setProvider(event.target.value as ProviderId);
                setModel('');
                setTested(false);
              }}
            >
              {PROVIDERS.map((item) => (
                <MenuItem key={item.id} value={item.id}>
                  {item.label}
                </MenuItem>
              ))}
            </Select>
          </FormControl>

          <TextField
            label="API key"
            type="password"
            value={apiKey}
            onChange={(event) => onApiKeyChange(event.target.value)}
            helperText={
              provider !== 'auto' ? `Detected/selected provider: ${providerOption?.label}` : 'Paste a key to auto-detect the provider'
            }
            required
            fullWidth
            autoFocus
          />

          <TextField
            label="Endpoint"
            value={endpoint}
            onChange={(event) => {
              setEndpoint(event.target.value);
              setTested(false);
            }}
            placeholder="https://resource.openai.azure.com"
            required={providerOption?.requiresEndpoint}
            fullWidth
          />

          <Autocomplete
            freeSolo
            options={providerOption?.models ?? []}
            value={model}
            onInputChange={(_event, value) => {
              setModel(value);
              setTested(false);
            }}
            renderInput={(params) => (
              <TextField {...params} label="Model or deployment" placeholder="gpt-4o or Azure deployment name" fullWidth />
            )}
          />

          <Button
            variant="outlined"
            startIcon={<TestIcon />}
            onClick={() => testMutation.mutate()}
            disabled={testMutation.isPending || apiKey.length < 8}
          >
            Test connection
          </Button>

          {testMutation.isPending && <Alert severity="info">Sending a test message to the provider...</Alert>}
          {testMutation.isError && <Alert severity="error">Connection test failed: {errorDetail(testMutation.error)}</Alert>}
          {tested && testMutation.data && (
            <Alert severity="success">
              Connected to {testMutation.data.provider} ({testMutation.data.model}). Reply: &ldquo;{testMutation.data.reply}&rdquo;
            </Alert>
          )}
          {saveMutation.isError && <Alert severity="error">{errorDetail(saveMutation.error)}</Alert>}
        </Stack>
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 3 }}>
        <Button
          variant="contained"
          disabled={!tested || saveMutation.isPending}
          onClick={() => saveMutation.mutate()}
        >
          Save &amp; Continue
        </Button>
      </DialogActions>
    </Dialog>
  );
}
