apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: production
  labels: { app: upload-service }
spec:
  type: ClusterIP
  selector: { app: upload-service }
  ports:
    - { name: http, port: 8001, targetPort: 8001 }
