apiVersion: v1
kind: Service
metadata:
  labels:
    app: upload-service
  name: upload-service
  namespace: production
spec:
  clusterIP: 10.1.5.237
  clusterIPs:
  - 10.1.5.237
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: upload-service
  sessionAffinity: None
  type: ClusterIP
