apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-review-service
  name: ai-review-service
  namespace: production
spec:
  clusterIP: 10.1.77.188
  clusterIPs:
  - 10.1.77.188
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: ai-review-service
  sessionAffinity: None
  type: ClusterIP
