apiVersion: v1
kind: Service
metadata:
  labels:
    app: scoring-service
  name: scoring-service
  namespace: production
spec:
  clusterIP: 10.1.64.218
  clusterIPs:
  - 10.1.64.218
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    app: scoring-service
  sessionAffinity: None
  type: ClusterIP
