apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: production
spec:
  clusterIP: 10.1.119.121
  clusterIPs:
  - 10.1.119.121
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: api-gateway
  sessionAffinity: None
  type: ClusterIP
